import { defineConfig } from "oxlint";

export default defineConfig({
    rules: {
        "typescript/ban-ts-comment": "warn",
        "typescript/no-duplicate-type-constituents": "warn",
        "typescript/no-empty-object-type": "off",
        "typescript/no-explicit-any": "warn",
        "typescript/no-extra-non-null-assertion": "warn",
        "typescript/no-namespace": "warn",
        "typescript/no-redundant-type-constituents": "warn",
        "typescript/no-require-imports": "warn",
        "typescript/no-this-alias": "warn",
        "typescript/no-unnecessary-type-assertion": "warn",
        "typescript/no-unnecessary-type-constraint": "warn",
        "typescript/only-throw-error": "warn",
        "typescript/prefer-as-const": "warn",
        "typescript/prefer-namespace-keyword": "warn",
        "typescript/prefer-promise-reject-errors": "warn",
        "typescript/require-await": "off",
        "typescript/restrict-template-expressions": "warn",
        "typescript/triple-slash-reference": "warn",
        "typescript/unbound-method": "off",
        "import/no-relative-parent-imports": "warn",
        "no-case-declarations": "warn",
        "no-constant-condition": "warn",
        "no-control-regex": "warn",
        "no-debugger": "warn",
        "no-empty": "warn",
        "no-empty-pattern": "warn",
        "no-empty-static-block": "warn",
        "no-extra-boolean-cast": "warn",
        "no-fallthrough": "warn",
        "no-irregular-whitespace": "warn",
        "no-prototype-builtins": "warn",
        "no-regex-spaces": "warn",
        "no-self-assign": "warn",
        "no-unassigned-vars": "warn",
        "no-unused-expressions": "warn",
        "no-unused-labels": "warn",
        "no-unused-private-class-members": "warn",
        "no-unused-vars": "warn",
        "no-useless-catch": "warn",
        "no-useless-escape": "warn",
        "prefer-const": "warn",
        "prefer-rest-params": "warn",
        "prefer-spread": "warn",
        "preserve-caught-error": "warn",
        "require-yield": "warn",

        "@typescript-eslint/no-shadow": "warn",
        "no-console": "warn",
        eqeqeq: "warn",
        "no-multi-assign": "warn",
        "no-else-return": "warn",
        "no-lonely-if": "warn",
        "no-useless-return": "warn",

        "no-eval": "warn",
        "no-caller": "warn",
        "no-extend-native": "warn",
        "no-extra-bind": "warn",
        "no-proto": "warn",
        "no-sequences": "warn",
        "no-useless-concat": "warn",
        "no-useless-rename": "warn",
        "prefer-template": "warn",

        "import/extensions": [
            "warn",
            "always",
            {
                ignorePackages: true,
            },
        ],
    },
});
